version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./api
      dockerfile: dockerfile
    ports:
      - "9010:9010"
    depends_on:
      - mongodb

  frontend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongodb_data:
